import {state,newLayer,selected} from './state.js';import {renderEditor,applyPixelFilter} from './canvas.js';
export const toolNames={move:'Move Tool',marquee:'Rectangular Marquee',lasso:'Lasso Tool',wand:'Magic Wand',crop:'Crop Tool',eyedropper:'Eyedropper',brush:'Brush Tool',pencil:'Pencil Tool',eraser:'Eraser Tool',bucket:'Paint Bucket',gradient:'Gradient Tool',blur:'Blur Tool',sharpen:'Sharpen Tool',text:'Type Tool',shape:'Shape Tool',zoom:'Zoom Tool',hand:'Hand Tool'};
const value=id=>Number(document.querySelector(`#${id}`)?.value||100);
export const toolName=tool=>toolNames[tool]||tool;
export function drawAt(point,erase=false){const layer=selected();if(!layer||layer.locked)return false;const context=layer.canvas.getContext('2d');context.save();context.globalAlpha=value('toolOpacity')/100;context.globalCompositeOperation=erase?'destination-out':'source-over';context.fillStyle=state.fg;context.beginPath();context.arc(point.x,point.y,value('toolSize')/2,0,Math.PI*2);context.fill();context.restore();return true}
export function moveLayer(dx,dy){const layer=selected();if(!layer||layer.locked)return false;layer.x+=dx;layer.y+=dy;return true}
export function addText(point,record){const text=prompt('Text:','Text layer');if(!text)return;const layer=newLayer(text,'text');layer.text=text;const context=layer.canvas.getContext('2d');context.fillStyle=state.fg;context.font=`${value('textSize')||32}px Arial`;context.fillText(text,point.x,point.y);state.layers.push(layer);state.selectedId=layer.id;record('Create text layer')}
export function addShape(start,end,record){const layer=newLayer('Shape','shape');const context=layer.canvas.getContext('2d');const kind=document.querySelector('#shapeKind')?.value||'rectangle';context.fillStyle=state.fg;context.strokeStyle=state.bg;context.lineWidth=value('shapeWidth')||2;const x=Math.min(start.x,end.x),y=Math.min(start.y,end.y),w=Math.abs(end.x-start.x),h=Math.abs(end.y-start.y);context.beginPath();if(kind==='ellipse')context.ellipse(x+w/2,y+h/2,w/2,h/2,0,0,Math.PI*2);else if(kind==='line'){context.moveTo(start.x,start.y);context.lineTo(end.x,end.y)}else context.rect(x,y,w,h);if(kind==='line')context.stroke();else{context.fill();context.stroke()}state.layers.push(layer);state.selectedId=layer.id;record(`Create ${kind}`)}
export function addLayer(record){const layer=newLayer();state.layers.push(layer);state.selectedId=layer.id;record('New layer')}
export function duplicateLayer(record){const layer=selected();if(!layer)return;const copy=newLayer(`${layer.name} copy`,layer.type);copy.canvas.getContext('2d').drawImage(layer.canvas,0,0);Object.assign(copy,{opacity:layer.opacity,blend:layer.blend,x:layer.x+10,y:layer.y+10,scaleX:layer.scaleX,scaleY:layer.scaleY,rotation:layer.rotation});state.layers.splice(state.layers.indexOf(layer)+1,0,copy);state.selectedId=copy.id;record('Duplicate layer')}
export function deleteLayer(record){const index=state.layers.findIndex(layer=>layer.id===state.selectedId);if(index<0)return;state.layers.splice(index,1);state.selectedId=state.layers[Math.max(0,index-1)]?.id||null;record('Delete layer')}
export function filter(name,record){const filters={grayscale:data=>{for(let i=0;i<data.length;i+=4){const v=.299*data[i]+.587*data[i+1]+.114*data[i+2];data[i]=data[i+1]=data[i+2]=v}},invert:data=>{for(let i=0;i<data.length;i+=4){data[i]=255-data[i];data[i+1]=255-data[i+1];data[i+2]=255-data[i+2]}},sepia:data=>{for(let i=0;i<data.length;i+=4){const[r,g,b]=[data[i],data[i+1],data[i+2]];data[i]=Math.min(255,r*.393+g*.769+b*.189);data[i+1]=Math.min(255,r*.349+g*.686+b*.168);data[i+2]=Math.min(255,r*.272+g*.534+b*.131)}},brightness:data=>{for(let i=0;i<data.length;i+=4)data[i]=data[i+1]=data[i+2]=Math.min(255,data[i]+20)}};if(filters[name]&&applyPixelFilter(filters[name]))record(`Filter: ${name}`)}
