import {state,newLayer,selected} from './state.js';import {renderEditor,applyPixelFilter,deleteSelection} from './canvas.js';
const tools={move:'Move Tool',marquee:'Rectangular Marquee',lasso:'Lasso Tool',wand:'Magic Wand',crop:'Crop Tool',eyedropper:'Eyedropper',brush:'Brush Tool',pencil:'Pencil Tool',eraser:'Eraser Tool',bucket:'Paint Bucket',gradient:'Gradient Tool',blur:'Blur Tool',sharpen:'Sharpen Tool',text:'Type Tool',shape:'Shape Tool',zoom:'Zoom Tool',hand:'Hand Tool'};
export function toolName(t){return tools[t]||t}
export function drawAt(p,erase=false){const l=selected();if(!l||l.locked)return;const x=l.canvas.getContext('2d');x.save();x.globalAlpha=Number(document.querySelector('#toolOpacity')?.value||100)/100;x.globalCompositeOperation=erase?'destination-out':'source-over';x.fillStyle=state.fg;x.beginPath();x.arc(p.x,p.y,Number(document.querySelector('#toolSize')?.value||24)/2,0,Math.PI*2);x.fill();x.restore();renderEditor()}
export function addText(p,record){const text=prompt('Text:','Text layer');if(!text)return;const l=newLayer('Text', 'text');l.text=text;const x=l.canvas.getContext('2d');x.fillStyle=state.fg;x.font=`${document.querySelector('#textSize')?.value||32}px Arial`;x.fillText(text,p.x,p.y);state.layers.push(l);state.selectedId=l.id;record('Create text layer');renderEditor()}
export function addShape(start,end,record){const l=newLayer('Shape','shape');const x=l.canvas.getContext('2d');x.fillStyle=state.fg;x.strokeStyle=state.bg;x.lineWidth=2;x.fillRect(start.x,start.y,end.x-start.x,end.y-start.y);state.layers.push(l);state.selectedId=l.id;record('Create shape');renderEditor()}
export function addLayer(record){const l=newLayer();state.layers.push(l);state.selectedId=l.id;record('New layer');renderEditor()}
export function duplicateLayer(record){const l=selected();if(!l)return;const n=newLayer(`${l.name} copy`,l.type);n.canvas.getContext('2d').drawImage(l.canvas,0,0);Object.assign(n,{opacity:l.opacity,blend:l.blend,x:l.x+10,y:l.y+10,scaleX:l.scaleX,scaleY:l.scaleY,rotation:l.rotation});state.layers.splice(state.layers.indexOf(l)+1,0,n);state.selectedId=n.id;record('Duplicate layer');renderEditor()}
export function deleteLayer(record){const i=state.layers.findIndex(l=>l.id===state.selectedId);if(i<0)return;state.layers.splice(i,1);state.selectedId=state.layers[Math.max(0,i-1)]?.id||null;record('Delete layer');renderEditor()}
export function filter(name,record){const f={grayscale:d=>{for(let i=0;i<d.length;i+=4){const v=.299*d[i]+.587*d[i+1]+.114*d[i+2];d[i]=d[i+1]=d[i+2]=v}},invert:d=>{for(let i=0;i<d.length;i+=4){d[i]=255-d[i];d[i+1]=255-d[i+1];d[i+2]=255-d[i+2]}},sepia:d=>{for(let i=0;i<d.length;i+=4){const[r,g,b]=[d[i],d[i+1],d[i+2]];d[i]=Math.min(255,r*.393+g*.769+b*.189);d[i+1]=Math.min(255,r*.349+g*.686+b*.168);d[i+2]=Math.min(255,r*.272+g*.534+b*.131)}},brightness:d=>{for(let i=0;i<d.length;i+=4){d[i]=Math.min(255,d[i]+20);d[i+1]=Math.min(255,d[i+1]+20);d[i+2]=Math.min(255,d[i+2]+20)}},blur:d=>{}}[name];if(f){applyPixelFilter(f);record(`Filter: ${name}`);renderEditor()}}
